Story/demo 3
orgramo/test-git-branch-flow pull request #7
Opened 2020-05-02 16:20 UTC by ramo

2020-07-07 11:56 UTC, ramo commented
this is a test comment.

2020-07-07 11:58 UTC, ramo-test requested changes

2020-07-07 11:58 UTC, ramo-test commented on file1.txt
> -ramo-test added something for story/demo-2
Do the requested change as per our discussion.

2020-07-07 12:22 UTC, ramo-test requested changes

2020-07-07 12:22 UTC, ramo-test commented on file1.txt
> +This is a test file.
this is again a test.

2020-07-07 12:24 UTC, ramo-test requested changes

2020-07-07 12:24 UTC, ramo-test commented on file1.txt
> -
add something.

2020-07-07 14:32 UTC, ramo commented on file1.txt
> +This is a test file.
test

2020-07-07 14:32 UTC, ramo-test commented
testing a comment.

2020-07-07 14:33 UTC, ramo-test commented
test

2020-07-07 14:34 UTC, ramo-test commented on file1.txt
> +This is a test file.
test

2020-07-07 14:42 UTC, ramo commented on file1.txt
> +This is a test file.
test

2020-07-07 14:42 UTC, ramo-test commented
test

2020-07-09 18:51 UTC, ramo-digisight requested changes

2020-07-09 18:51 UTC, ramo-digisight commented on file1.txt
> -This is a test file.
What is this?

2020-07-09 19:29 UTC, merged